/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficos;

import java.awt.Font;
import java.util.Iterator;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * Declaracion de la clase Mostrar_tabla
 * @author Ingrid Paola Lopez Niño, Jiménez Pérez Pedro, Alonso González Alejandro Javier, Azcona González José Antonio, Chávez Aquino Daniel Felipe
 * @version 06/12/2016
 */
public class Mostrar_tabla extends javax.swing.JFrame {
    ListaLigada<Tabla> listaDeTablas = new ListaLigada<Tabla>();
    private String aux[];
    private String aux2[];
    /**
     * Metodo que regresa una Lista Ligada de Tabla
     * @return listaDeTablas
     */
    public ListaLigada<Tabla> regresaLista(){
        return listaDeTablas;
    }
    /**
     * Constructor de la clase que tiene un parametro
     * @param listaDeTablas Es un parametro de tipo Lista Ligada
     */
    public Mostrar_tabla(ListaLigada<Tabla> listaDeTablas) {
        this.listaDeTablas=listaDeTablas;
        initComponents();
        this.setResizable(false);
        this.setTitle("Mostrar tabla");
        agregarItems();
    }
    /**
     * Costructor de la clase sin parametro donde se implementan las propiedades de la misma
     * @version 06/12/2016
     */
    public Mostrar_tabla() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Mostrar tabla");
        agregarItems();
    }
    /**
     * Metodo para agregar los campos al jComboBox
     * @version 06/12/2016
     */
    public void agregarItems(){
        Crear_tabla c=new Crear_tabla();
        Iterator<String> iter = c.getTablas().iterator();
        while(iter.hasNext()){
            String s=iter.next();
            aux=s.split("/");
    
            jComboBox1.addItem(aux[0]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel1.setText("Tabla");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 33, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 30, 226, -1));

        jButton1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 68, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setText("Ordenar por");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 72, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 69, 203, -1));

        jComboBox3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Burbuja", "Burbuja con señal", "Shaker Sort", "Inserción directa (Baraja)", "Inserción binaria", "Selección directa", "Shell Sort", "Quick Sort" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 69, 199, -1));

        jButton2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 475, -1, 33));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 84, 29));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 176, 490, 240));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/444.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Metodo del boton de aceptar
     * @param evt Es un parametro de ActionEvent
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Metodo del boton del jComboBox de la tabla
     * @param evt Es un parametro de ActionEvent
     */
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jComboBox2.removeAllItems();
        Crear_tabla c=new Crear_tabla();
        Iterator<String> iter = c.getTablas().iterator();
        while(iter.hasNext()){
            String s=iter.next();
            aux=s.split("/");
            aux2=s.replaceFirst(aux[0],"").replace('/',' ').split(",");
            if(jComboBox1.getSelectedItem().equals(aux[0])){
                for(int i=0; i<aux2.length;i++){
                jComboBox2.setFont(new Font("Georgia", Font.PLAIN, 12));
                   // JOptionPane.showMessageDialog(null, aux[1]);
                jComboBox2.addItem(aux2[i]);
                }
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    /**
     * Metodo del jComboBox donde nos dice como queremos ordenar
     * @param evt Es un parametro de ActionEvent
     */
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
    /**
     * Metodo del JComboBox donde nos dice que metodo usar
     * @param evt Es un parametro de ActionEvent
     */
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed
    /**
     * Metodo del boton Mostrar
     * @param evt Es un parametro de ActionEvent
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Ordenamiento ordenar = new Ordenamiento();
        String op=""+jComboBox3.getSelectedItem();
        switch(op){
            case "Burbuja":
                
        }
        
      String datos="";
        //Tabla datosTabla=(listaDeTablas.buscarTabla(""+jComboBox1.getSelectedItem()));
        //String datos=""+datosTabla.getRegistros().recorrer2(datosTabla.getRegistros().getInicio());
         
         datos+=" "+listaDeTablas.buscarTabla(""+jComboBox1.getSelectedItem()).getRegistros().toString();
       
       jTextArea1.setText(datos);
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Este es el metodo del JComboBox
     * @return jComboBox1
     */
    public JComboBox getjComboBox1() {
        return jComboBox1;
    }
    /**
     * Este metodo no regresa nada
     * @param jComboBox1 Es un parametro de JComboBox
     */
    public void setjComboBox1(JComboBox jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar_tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar_tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar_tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar_tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar_tabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
